[project]
name = 'Blockchain-Based-Urban-Traffic-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.congestion-prediction]
path = 'contracts/congestion-prediction.clar'
clarity_version = 2
epoch = 2.5

[contracts.intersection-verification]
path = 'contracts/intersection-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-analysis]
path = 'contracts/performance-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.signal-cordinator]
path = 'contracts/signal-cordinator.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-flow]
path = 'contracts/vehicle-flow.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
